export * as baseUtils from './common/base.common';
export * from './common/cookie.common';
export * from './common/storage.common';
export * from './common/descriptor.common';
export * from './common/crypto.common';
export * from './common/reg.common';
import extArray, { IArrayExtension } from './extension/array.extension';
import extDate, { IDateExtension } from './extension/date.extension';
import extNumber, { INumberExtension } from './extension/number.extension';
import extString, { IStringExtension } from './extension/string.extension';
export { extArray, extDate, extNumber, extString, IArrayExtension, IDateExtension, INumberExtension, IStringExtension, };
declare function ext(date: Date): IDateExtension;
declare function ext(str: string): IStringExtension;
declare function ext(num: number): INumberExtension;
declare function ext<T>(arr: T[]): IArrayExtension<T>;
export default ext;
